### ISSUE TITLE
Check for post-2020 commits to interactive template that should be migrated back here

### ISSUE THREAD

**Issue by alykat** [nprapps/elections22#1]
https://github.com/nprapps/interactive-template/commits/master

**Comment by jsfenfen** [comment]
googleapi version is updated https://github.com/nprapps/interactive-template/commit/2c1814bec19d24312bb1dcfc6ccb99b51c42c8f1  . Footer copyright is updated.

**Comment by jsfenfen** [comment]
Tracking is up to date - see:  https://github.com/nprapps/elections22/blob/main/src/js/lib/tracking.js  / https://github.com/nprapps/interactive-template/commit/bb8869a05e1aa810a8d90d28928e30f1ab9cfecf

**Comment by jsfenfen** [comment]
analytics partial is updated: https://github.com/nprapps/elections22/blob/main/src/partials/_analytics.html / https://github.com/nprapps/interactive-template/commit/48c318b702c6a7108f23352302177a66ba553c91

**Comment by jsfenfen** [comment]
consider camelcasing googleauth.js and googlesave.js for consistency, do not think these are called by others, but needs checking.


https://github.com/nprapps/interactive-template/commit/35c420a82e2e70c7e42069d171fa4ea1a3a379d4 / https://github.com/nprapps/elections22/tree/main/tasks
