### ISSUE TITLE
Possible for the inline version of BOP to stay side-by-side / not stack at the mobile breakpoint?

### ISSUE THREAD

**Issue by alykat** [nprapps/elections22#103]
Would be helpful for an iOS app hackaround DM is considering. The graphic would need to fit in a 300x250 space.

![image](https://user-images.githubusercontent.com/491318/199579357-53409ad1-f460-4430-af00-23869d506bf8.png)

**Comment by alykat** [comment]
Told Jared to pull this version of the URL for the iframe:
https://apps.npr.org/election-results-live-2022/embedBOP.html?inline=true&nprone=true

The child page might need to fire this bit of code?

```
window.webkit.messageHandlers.adHeight.postMessage(adHeight, '*');
```

Example of a page they're using for sponsorship: https://legacy.npr.org/assets/sponsorship/apps/html/home-screen.html

**Comment by jsfenfen** [comment]
Hmm, I think the links should be opening in a new window if it's embedded too

**Comment by alykat** [comment]
@jsfenfen good point. ticketing separately.
