### ISSUE TITLE
BOP: When embedded, links should open in a new window

### ISSUE THREAD

**Issue by alykat** [nprapps/elections22#104]
Currently not. See:
https://github.com/nprapps/elections22/blob/main/src/js/embedBOP.js#L238
https://github.com/nprapps/elections22/blob/main/src/js/embedBOP.js#L180
https://github.com/nprapps/elections22/blob/main/src/js/embedBOP.js#L137

_Originally posted by @jsfenfen in https://github.com/nprapps/elections22/issues/103#issuecomment-1301154749_

**Comment by jsfenfen** [comment]
closed in b5d45bdc2aa9096719e96494900574442f026aeb
