### ISSUE TITLE
Boards: When races are super-close/competitive, going to a decimal might be helpful

### ISSUE THREAD

**Issue by alykat** [nprapps/elections22#124]
Use case: Warnock / Walker both showing 49%, but Walker is highlighted as leading.

![image](https://user-images.githubusercontent.com/491318/200725791-ae5ba6e4-9f1a-4366-8085-2cab43da03ba.png)

**Comment by jsfenfen** [comment]
In GA you need 50% to avoid a runoff, so rounding 49.6 up might be more problematic than in other states
