### ISSUE TITLE
State pages: Update underlying comparative data

### ISSUE THREAD

**Issue by alykat** [nprapps/elections22#20]
Update underlying data for all the demographic trend charts and sortable tables (there are some python files in the repo that should help)

https://github.com/nprapps/elections22/blob/main/get_census_data.py
https://github.com/nprapps/elections22/blob/main/get_unemployment_data.py

**Comment by alykat** [comment]
There's a little more detail maybe in the readme for the 2021 instance of this project: https://github.com/nprapps/elections21-governors#getting-county-data

**Comment by jsfenfen** [comment]
need to eventually clean up helper script and commit, the data is updated, so closing
