### ISSUE TITLE
Alaska: Filter out results IDs for separate Ranked Choice Voting results

### ISSUE THREAD

**Issue by jsfenfen** [nprapps/elections22#49]
For the first time this cycle, Alaska is using ranked choice voting for house, senate and gubernatorial elections. This is handled in the AP's API as if there are two distinct contests: a "General" and an "RCV General Election" which have different race ids. 

Background: https://alaskapublic.org/2022/09/15/why-alaska-uses-ranked-choice-voting-and-what-we-know-about-how-it-affects-elections/

**Comment by jsfenfen** [comment]
Governor's race polling is thin, but this appears to be something that might occur https://projects.fivethirtyeight.com/polls/alaska/

**Comment by jsfenfen** [comment]
RCV was added to ELAPI in v3 and first used in the 22 primary, but a pretty exhaustive read of their docs didn't turn up any explanation. The release notes describe an election call status of "Awaiting Ranked Choice Results" to be: `AP assesses no candidate will win outright, and the election will proceed to election officials tabulating ranked choice vote results.`

AK voting rules advance the top *4* finishers from the primary to the general so it's likely we'll see this status come up.

**Comment by alykat** [comment]
I did find one additional detail in the AP elections testing advisory for Alaska:

> Results from the first round will be in the general election race type. **Ranked choice results will be available at the end of tabulation (15 days after Election Day, Nov. 23)** in the ranked choice “RCV General Election” race type.
