### ISSUE TITLE
Sponsorship ad unit loads inconsistently

### ISSUE THREAD

**Issue by alykat** [nprapps/elections22#58]
Erica notes that the sponsorship unit sometimes doesn't load. (Use case: On desktop, clicking from the Senate board to the House board, the ad didn't show up on the House page.) I've also noticed inconsistencies on the state pages — sometimes the ad unit doesn't load at first, and I wonder if this has to do with [the way the code is lazy-loaded](https://github.com/nprapps/elections22/blob/main/src/js/components/ad.js#L35-L46). One other thing to test is whether this is any better on prod (https) vs. stage (http).

**Comment by alykat** [comment]
@alykat ask sponsorship to make sure we're getting a test ad so something loads in that spot for us to test?

**Comment by jsfenfen** [comment]
Is the ad supposed to appear on state pages? It appears in a #bottom div and looks like it is blocked by 
`[data-view="StateResults"] #bottom {
  display: none !important;
}`

It is showing up consistently for me on https on others pages, but a page reroute is not treated as a new impression, which may or may not be what is desired.

**Comment by jsfenfen** [comment]
Confirmed the ad code is trying to load, no errors are being thrown, but google seems to silently fail kind of a lot?
