### ISSUE TITLE
Integrate OneTrust

### ISSUE THREAD

**Issue by alykat** [nprapps/elections22#6]
We need to get OneTrust privacy management code on ALL public-facing pages — both standalones and embeds, no matter how small.

**Comment by jsfenfen** [comment]
I think this is closed in [6b808f7](https://github.com/nprapps/elections22/commit/6b808f765f21299fad519abd66757f8ccdf2be4a)

**Comment by jsfenfen** [comment]
Need to check on embed situation

**Comment by alykat** [comment]
Not needed for the customizer page.

I think this is pretty much good, but leaving the ticket open until we can deploy a version to verify that everything's working ok.

**Comment by alykat** [comment]
Based on @kokonakajima's findings with testing so far, we may need to make an adjustment to the analytics script to account for onetrust status.
