### ISSUE TITLE
Alaska RCV explainer if needed

### ISSUE THREAD

**Issue by jsfenfen** [nprapps/elections22#62]
If we need to link to an explainer on Alaska voting, here's one from AP: https://apnews.com/article/alaska-ranked-choice-voting-5ae6c163af2f8a70a8f90928267c4086

**Comment by jsfenfen** [comment]
"This fall’s election is set for Nov. 8, but that’s just round one. Additional rounds of counting, if necessary, won’t happen until Nov. 23."

**Comment by alykat** [comment]
Added placeholder text as the intro to the AK state page. Edit at will.
