### ISSUE TITLE
double check senate math

### ISSUE THREAD

**Issue by jsfenfen** [nprapps/elections22#63]
Questions re:
- Updating the composition of senate seats that aren't up this election
- Total number of uncalled races is off ATM, hmm

**Comment by alykat** [comment]
Good call. If you haven't found it already, that can be updated in the `inactive_senate_races` sheet of the config spreadsheet.

**Comment by jsfenfen** [comment]
Inactive seats is updated. Cook says the following: https://www.cookpolitical.com/ratings/senate-race-ratings

Currently, Democrats control 48 seats. Republicans control 50 seats.

14 Democrat-controlled seats and 21 Republican-controlled seats are up for election.

There are 2 Independent seats, and none are up for election. These seats caucus with Democrats."

**Comment by jsfenfen** [comment]
Removing the RCV for alaska still leaves an off-by-one error. I think. Keeping open.

**Comment by jsfenfen** [comment]
The issue appears to be that AP is returning two races for california: 

8516 - "General" and 8964 - "Special General" ; the 8964 result says it is part of the 2016 term.

**Comment by jsfenfen** [comment]
This is a legit--if stupid--consequence of CA law https://www.capradio.org/articles/2022/10/17/us-sen-alex-padilla-will-appear-on-californias-june-primary-ballot-twice-heres-why/

**Comment by jsfenfen** [comment]
So short answer is -- I think -- that we should suppress the results of the 2016 seat contest. They have no bearing on the balance of power.
