### ISSUE TITLE
Make sure share pages are up-to-date

### ISSUE THREAD

**Issue by alykat** [nprapps/elections22#70]
The `base` variable at least needs to be updated, pending a decision on our deploy path. (Or is there a way to do this that pulls from the config / doesn't hard-code the URL?) Blocked by #36 

https://github.com/nprapps/elections22/blob/main/src/_office_social.html
https://github.com/nprapps/elections22/blob/main/src/_state_social.html

**Comment by jsfenfen** [comment]
Updated the base path
