### ISSUE TITLE
Duplicate ME and NE entries in the footer

### ISSUE THREAD

**Issue by alykat** [nprapps/elections22#71]
I assume this is left over from accounting for ME/NE electoral votes. 
<img width="338" alt="image" src="https://user-images.githubusercontent.com/491318/197352397-7c27b5f5-5d76-4d4f-aba7-e14c6cd16bbb.png">

**Comment by jsfenfen** [comment]
Closed in d5e86cc912c862eec2744cffc8b7d0681898e972
