### ISSUE TITLE
It seems like timestamp stops updating if data doesn't change? 

### ISSUE THREAD

**Issue by jsfenfen** [nprapps/elections22#72]
Not sure if that's actually what's happening? 

No change since last request for 2022-11-08_level=state&officeID=H,I
Loaded offline data from temp/948b508c2891a6f897738ba49fedc444.json

**Comment by alykat** [comment]
I think that's the desired behavior, assuming the timestamps aren't updating in the underlying data?

For the House board, for example, if I'm reading this right it look like it picks the most recent timestamp from the data to show on the page: https://github.com/nprapps/elections22/blob/main/src/js/components/boardHouse/index.js#L19

Or for state pages: https://github.com/nprapps/elections22/blob/main/src/js/components/stateResults/index.js#L27-L36

**Comment by jsfenfen** [comment]
Makes sense! closing
