### ISSUE TITLE
House "not yet called" not adding up correctly

### ISSUE THREAD

**Issue by alykat** [nprapps/elections22#76]
Should this be 435?

<img width="391" alt="image" src="https://user-images.githubusercontent.com/491318/198075214-78bb9500-39a6-4c5e-b801-7e9c64004bdc.png">

**Comment by jsfenfen** [comment]
This goes away if the bars are swapped in...

**Comment by jsfenfen** [comment]
It looks like there's a special election in Indiana for the end of the unexpired term of district 2, so excluding this fixes it.
