### ISSUE TITLE
If there's only one race we're following in a state, that should appear by default on the "Key" tab

### ISSUE THREAD

**Issue by alykat** [nprapps/elections22#86]
thinking in particular of DE, DC but there are may be a handful of others

![image](https://user-images.githubusercontent.com/491318/198371637-2dfe08bb-48dd-424c-966b-db62dabb521a.png)

**Comment by alykat** [comment]
alternately (thinking of MS), if there's no key race (and just a handful of house races), should there be a "key" tab at all? or should "key" just show all the house races?

**Comment by jsfenfen** [comment]
This appears to be limited to MS and DE (there's now a key initiative in DC). In those cases, all races are shown.
