### ISSUE TITLE
Improve SEO

### ISSUE THREAD

**Issue by alykat** [nprapps/elections22#9]
If we have time: The way the project was engineered, as a one-page app, was great for speed/responsiveness, but bad for SEO. Can this be rethought?

One possibility Thomas raised last time was to create state-specific "stub" pages

**Comment by alykat** [comment]
Collecting some of the initial ideas batted around that don't involve re-engineering the site:

* Piggyback on the stub pages we're [already creating/redirecting](https://github.com/nprapps/elections22/blob/main/tasks/build.js#L66-L81) for social
* Create stub pages that somehow impersonate the true/hashed URLs
* Create a sitemap based on the stub pages and submit *those* for indexing?
* Any useful strategies involving canonical urls or robots.txt?

Documentation:
* canonical URLs: https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls
* robots.txt: https://developers.google.com/search/docs/crawling-indexing/robots/robots_txt

Also:
* @jsfenfen has asked Google to re/index the 2020 results pages (using the House board as a test) and we'll see what we get back

**Comment by alykat** [comment]
Some kind of dynamic rendering solution + a sitemap for key pages?
https://developers.google.com/search/docs/crawling-indexing/javascript/dynamic-rendering

**Comment by jsfenfen** [comment]
I submitted a sitemap for the '20 elections. After 48 hours the fix we submitted is still unvalidated, but it seems like this is gonna need a belt and suspenders approach.

**Comment by jsfenfen** [comment]
Sitemap and stub 22 results submitted to google. It's not clear we will have a chance to fix this; google has now taken *more than 120 hours* to validate missing canonical urls on 170 pages. Crazy how much less performant google is compared to ten years ago.

**Comment by jsfenfen** [comment]
I moved the canonical url hack into the page head. This canonical tag is now showing in the google search console' "test live url" option.

**Comment by alykat** [comment]
@jsfenfen did you try also updating the title and meta description w/ the same hack?

if i search `npr election results 2022 michigan` i'm actually seeing our results come up (albeit linked to the house board).

<img width="654" alt="image" src="https://user-images.githubusercontent.com/491318/199633089-3249e601-bae7-4896-9b72-82b7bdce726e.png">
