### ISSUE TITLE
Manual call option for senate

### ISSUE THREAD

**Issue by jsfenfen** [nprapps/elections22#95]
The app logic doesn't place a checkmark next to either party until it gets to 51 senators. But realistically D's win at 50D's plus 2 independents who caucus with dems (Bernie Sanders / Angus King ). 

 It's probalby a good idea to have a solution on hand if we get to this kinda crazy state, though the odds are against it.

**Comment by alykat** [comment]
Will handle via a message under the "senate" board header, not a checkmark
